CREATE DATABASE DelBicos;


CREATE TABLE USUARIO
(
    ID_USUARIO NUMERIC(18,0) IDENTITY(1,1) PRIMARY KEY NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(30) NOT NULL,
    TELEFONE VARCHAR(15) NULL,
    SENHA VARCHAR(30) NOT NULL
);


CREATE TABLE CLIENTE
(
    ID_CLIENTE NUMERIC(18,0) IDENTITY(1,1) PRIMARY KEY NOT NULL,
    ID_USUARIO NUMERIC(18,0) NOT NULL,
    CEP VARCHAR(8) NOT NULL,
    LOGRADOURO VARCHAR(50) NOT NULL,
    NUMERO VARCHAR(10) NOT NULL,
    COMPLEMENTO VARCHAR(50) NULL,
    CIDADE VARCHAR(30) NOT NULL,
    ESTADO CHAR(2) NOT NULL,
    CPF VARCHAR(11) NOT NULL,
    CONSTRAINT FK_CLIENTE_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);


CREATE TABLE PARCEIRO
(
    ID_PARCEIRO NUMERIC(18,0) IDENTITY(1,1) PRIMARY KEY NOT NULL,
    ID_USUARIO NUMERIC(18,0) NOT NULL,
    CNPJ VARCHAR(14) NOT NULL,
    CPF VARCHAR(11) NOT NULL,
    CEP VARCHAR(8) NOT NULL,
    LOGRADOURO VARCHAR(50) NOT NULL,
    NUMERO VARCHAR(10) NOT NULL,
    COMPLEMENTO VARCHAR(50) NULL,
    CIDADE VARCHAR(30) NOT NULL,
    ESTADO CHAR(2) NOT NULL,
    CONSTRAINT FK_PARCEIRO_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);


CREATE TABLE ADMIN
(
    ID_ADMIN NUMERIC(18,0) IDENTITY(1,1) PRIMARY KEY NOT NULL,
    ID_USUARIO NUMERIC(18,0) NOT NULL,
    CONSTRAINT FK_ADMIN_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);


CREATE TABLE CATEGORIA
(
    ID_CATEGORIA NUMERIC(18,0) IDENTITY(1,1) PRIMARY KEY NOT NULL,
    NOME VARCHAR(20) NOT NULL,
    DESCRICAO VARCHAR(100) NULL
);


CREATE TABLE ESPECIALIDADE
(
    ID_ESPECIALIDADE NUMERIC(18,0) IDENTITY(1,1) PRIMARY KEY NOT NULL,
    ID_CATEGORIA NUMERIC(18,0) NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    MINUTOS NUMERIC(18,0) NOT NULL,
    VALOR FLOAT NOT NULL,
    DESCRICAO VARCHAR(100) NULL,
    CONSTRAINT FK_ESPECIALIDADE_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA)
);


CREATE TABLE AGENDA
(
    ID_AGENDA NUMERIC(18,0) IDENTITY(1,1) PRIMARY KEY NOT NULL,
    ID_ESPECIALIDADE NUMERIC(18,0) NOT NULL,
    ID_PARCEIRO NUMERIC(18,0) NOT NULL,
    DATA DATE NOT NULL,
    HORA_INICIO TIME NOT NULL,
    HORA_FIM TIME NOT NULL,
    DESCRICAO VARCHAR(100) NULL,
    STATUS CHAR(1) NOT NULL,
    CONSTRAINT FK_AGENDA_ESPECIALIDADE FOREIGN KEY (ID_ESPECIALIDADE) REFERENCES ESPECIALIDADE(ID_ESPECIALIDADE),
    CONSTRAINT FK_AGENDA_PARCEIRO FOREIGN KEY (ID_PARCEIRO) REFERENCES PARCEIRO(ID_PARCEIRO)
);


CREATE TABLE CONSULTA
(
    ID_CONSULTA NUMERIC(18,0) IDENTITY(1,1) PRIMARY KEY NOT NULL,
    ID_CLIENTE NUMERIC(18,0) NOT NULL,
    ID_AGENDA NUMERIC(18,0) NOT NULL,
    ID_PARCEIRO NUMERIC(18,0) NOT NULL,
    STATUS CHAR(1) NOT NULL,
    DESCRICAO VARCHAR(100) NULL,
    VALOR FLOAT NOT NULL,
    CONSTRAINT FK_CONSULTA_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
    CONSTRAINT FK_CONSULTA_AGENDA FOREIGN KEY (ID_AGENDA) REFERENCES AGENDA(ID_AGENDA),
    CONSTRAINT FK_CONSULTA_PARCEIRO FOREIGN KEY (ID_PARCEIRO) REFERENCES PARCEIRO(ID_PARCEIRO)
);


CREATE TABLE CHAMADO
(
    ID_CHAMADO NUMERIC(18,0) IDENTITY(1,1) PRIMARY KEY NOT NULL,
    ID_CONSULTA NUMERIC(18,0) NOT NULL,
    CATEGORIA CHAR(1) NOT NULL,
    TITULO VARCHAR(50) NOT NULL,
    DESCRICAO VARCHAR(100) NULL,
    STATUS CHAR(1) NOT NULL,
    CONSTRAINT FK_CHAMADO_CONSULTA FOREIGN KEY (ID_CONSULTA) REFERENCES CONSULTA(ID_CONSULTA)
);

